build: trusty
language: php
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false
script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover